name: Terraform Destroy per Branch

on:
  delete:
  
  workflow_dispatch:
    inputs:
      branch:
        description: "Name of the branch to be destroyed"
        required: false

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
          aws-region: eu-central-1

      - name: Destroy Terraform resources
        run: |
          cd Terraform
          BRANCH=${{ github.event.inputs.branch || github.event.ref_name }}
          SAFE_BRANCH=$(echo "$BRANCH" | tr '/' '-')
          terraform init \
            -backend-config="bucket=tf-bud-relo-state-bucket-f" \
            -backend-config="key=infra/${SAFE_BRANCH}/terraform.tfstate" \
            -backend-config="region=eu-central-1"

          terraform destroy -auto-approve \
            -var "branch_name=${SAFE_BRANCH}" \
            -var "aws_region=eu-central-1" \
            -var "key_name=mykeypair-aws" \
            -var "aws_instance_type=t3.small"
