name: Terraform Apply per Branch

on:
  push:
    branches:
      [ _main]
  workflow_dispatch:

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v5

      # Extract the branch name and make it safe for S3 bucket
      - name: Extract branch name
        id: extract_branch
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          SAFE_BRANCH=$(echo "$BRANCH_NAME" | tr '/' '-' | tr '[:upper:]' '[:lower:]')
          echo "branch_name=$SAFE_BRANCH" >> $GITHUB_OUTPUT
           "
        # Generate Fake Data locally
      - name: run Faker.js to generate test data
        run: |
         npm install  @faker-js/faker
         node scripts/generateTestData.js
          
      # Setup Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
          aws-region: eu-central-1

      # Create S3 bucket for Terraform state if it does not exist
      - name: Create S3 bucket if missing
        run: |
          SAFE_BRANCH=${{ steps.extract_branch.outputs.branch_name }}
          BUCKET_NAME="tf-bud-relo-state-bucket-${SAFE_BRANCH}"
          aws s3api head-bucket --bucket $BUCKET_NAME 2>/dev/null || \
          aws s3api create-bucket \
            --bucket $BUCKET_NAME \
            --region eu-central-1 \
            --create-bucket-configuration LocationConstraint=eu-central-1

      # Initialize and apply Terraform
      - name: Terraform Init & Apply
        run: |
          cd budget-infra
          terraform init \
            -backend-config="bucket=tf-bud-relo-state-bucket-${{ steps.extract_branch.outputs.branch_name }}" \
            -backend-config="key=infra/${{ steps.extract_branch.outputs.branch_name }}/terraform.tfstate" \
            -backend-config="region=eu-central-1"

          terraform apply \
            -var "branch_name=${{ steps.extract_branch.outputs.branch_name }}" \
            -var "db_password=${{ secrets.DB_PASSWORD }}" \
            -var "key_name=ssh-budget-reloaded-key" \
            -auto-approve

      # Wait a bit for EC2 instance to be ready for SSH
      - name: Wait for EC2 SSH
        run: sleep 30

      # Setup SSH key for EC2 access
      - name: Setup SSH key
        run: |
          ip=$(terraform -chdir=budget-infra output -raw public_ip)
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_EC2_KEY_PEM }}" > ~/.ssh/myPrivateKey
          chmod 400 ~/.ssh/myPrivateKey
          ssh-keyscan -H $ip >> ~/.ssh/known_hosts

      # Send Test Data to populate API/DB running on EC2
      - name: Seed EC2 backend with Faker.js data
        run: |
          npm install  @faker-js/faker
          node scripts/generateTestData.js

      # Install Docker and Docker Compose V2 on EC2
      - name: Install Docker & Docker Compose
        run: |
          ip=$(terraform -chdir=budget-infra output -raw public_ip)
          ssh -i ~/.ssh/myPrivateKey ubuntu@$ip "
            sudo apt update
            sudo apt install docker.io -y
            sudo usermod -aG docker ubuntu
            sudo mkdir -p /usr/local/lib/docker/cli-plugins
            DOCKER_COMPOSE_VERSION=2.27.0
            sudo curl -SL https://github.com/docker/compose/releases/download/v\${DOCKER_COMPOSE_VERSION}/docker-compose-linux-x86_64 -o /usr/local/lib/docker/cli-plugins/docker-compose
            sudo chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
          "

      # Deploy the app on EC2
      - name: Deploy App
        run: |
          ip=$(terraform -chdir=budget-infra output -raw public_ip)
          ENDPOINT=$(terraform -chdir=budget-infra output -raw rds_endpoint)
          HOST=$(echo "$ENDPOINT" | cut -d':' -f1)

          # Copy project files to EC2
          scp -i ~/.ssh/myPrivateKey -r /home/runner/work/Budget_Manager_Reloaded/Budget_Manager_Reloaded ubuntu@$ip:/home/ubuntu
          # Install psql client if missing
          ssh -i ~/.ssh/myPrivateKey ubuntu@$ip "
            sudo apt update && sudo apt install -y postgresql-client
          "

          # Apply SQL schema
          ssh -i ~/.ssh/myPrivateKey ubuntu@$ip "
            PGPASSWORD='${{ secrets.DB_PASSWORD }}' psql -h '$HOST' -p 5432 -U postgres -f /home/ubuntu/Budget_Manager_Reloaded/backend/budget_2025-05-08.sql
          "
          # Create .env.local files and start containers
          ssh -i ~/.ssh/myPrivateKey ubuntu@$ip "
          # Create frontend environment file
          echo "DB_HOST=$HOST" >> "/home/ubuntu/Budget_Manager_Reloaded/backend/.env.local"
          # echo "REACT_APP_API_URL=http://$ip:5005"  > "/home/ubuntu/Budget_Manager_Reloaded/frontend/.env.local"
          export REACT_APP_API_URL=http://$ip:5005
          cd ~/Budget_Manager_Reloaded

            # # Stop any running containers and rebuild
          docker compose down -v || true
            # docker compose build --no-cache
          
          docker compose up -d --build
     


#      # Initialize PostgreSQL database schema
#      - name: Initialize DB schema
#        run: |
#          ip=$(terraform -chdir=budget-infra output -raw public_ip)
#          ENDPOINT=$(terraform -chdir=budget-infra output -raw rds_endpoint)
#          HOST=$(echo "$ENDPOINT" | cut -d':' -f1 | tr -d '\r\n')
#
#          # Install psql client if missing
#          ssh -i ~/.ssh/myPrivateKey ubuntu@$ip "
#            sudo apt update && sudo apt install -y postgresql-client
#          "
#
#          # Apply SQL schema
#          ssh -i ~/.ssh/myPrivateKey ubuntu@$ip "
#            PGPASSWORD='${{ secrets.DB_PASSWORD }}' psql -h '$HOST' -p 5432 -U postgres -f /home/ubuntu/Budget_Manager_Reloaded/backend/budget_2025-05-08.sql
#          "

          
