name: Terraform Apply per Branch

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Extract branch name
        id: extract_branch
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          SAFE_BRANCH=$(echo "$BRANCH_NAME" | tr '/' '-' | tr '[:upper:]' '[:lower:]')
          echo "branch_name=$SAFE_BRANCH" >> $GITHUB_OUTPUT

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
          aws-region: eu-central-1

    
      - name: Create S3 bucket if missing
        run: |
            SAFE_BRANCH=${{ steps.extract_branch.outputs.branch_name }}
            BUCKET_NAME="tf-bud-relo-state-bucket-${SAFE_BRANCH}"
            aws s3api head-bucket --bucket $BUCKET_NAME 2>/dev/null || \
            aws s3api create-bucket \
            --bucket $BUCKET_NAME \
            --region eu-central-1 \
            --create-bucket-configuration LocationConstraint=eu-central-1

      - name: Terraform Init & Apply
        run: |
          cd budget-infra
          terraform init \
            -backend-config="bucket=tf-bud-relo-state-bucket-${{ steps.extract_branch.outputs.branch_name }}" \
            -backend-config="key=infra/${{ steps.extract_branch.outputs.branch_name }}/terraform.tfstate" \
            -backend-config="region=eu-central-1"

          terraform apply \
            -var "branch_name=${{ steps.extract_branch.outputs.branch_name }}" \
            -var "db_password=${{ secrets.DB_PASSWORD }}"\
            -var "key_name=ssh-budget-reloaded-key" \
            -auto-approve

      - name: Wait for EC2 SSH
        run: sleep 30

      - name: Setup SSH key
        run: |
          ip=$(terraform -chdir=budget-infra output -raw public_ip)
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_EC2_KEY_PEM }}" > ~/.ssh/myPrivateKey
          chmod 400 ~/.ssh/myPrivateKey
          ssh-keyscan -H $ip >> ~/.ssh/known_hosts

      - name: Install Docker & Docker Compose
        run: |
                ip=$(terraform -chdir=budget-infra output -raw public_ip)
                ssh -i ~/.ssh/myPrivateKey ubuntu@$ip "sudo apt update"
                ssh -i ~/.ssh/myPrivateKey ubuntu@$ip "sudo apt install docker.io -y"
                ssh -i ~/.ssh/myPrivateKey ubuntu@$ip "sudo usermod -aG docker ubuntu"   
                ssh -i ~/.ssh/myPrivateKey ubuntu@$ip "sudo apt install docker-compose -y"

      - name: Deploy App
        run: |
            ip=$(terraform -chdir=budget-infra output -raw public_ip)
            ENDPOINT=$(terraform -chdir=budget-infra output -raw rds_endpoint)
            HOST=$(echo "$ENDPOINT" | cut -d':' -f1)

            scp -i ~/.ssh/myPrivateKey -r /home/runner/work/Budget_Manager_Reloaded/Budget_Manager_Reloaded ubuntu@$ip:/home/ubuntu

            ssh -i ~/.ssh/myPrivateKey ubuntu@$ip "
            export DB_HOST=$HOST
            export DB_PASSWORD='${{ secrets.DB_PASSWORD }}'
            cd /home/ubuntu/Budget_Manager_Reloaded
            echo \"DB_HOST=$DB_HOST\" > backend/.env.local
            echo \"DB_PASSWORD=$DB_PASSWORD\" >> backend/.env.local
            echo \"REACT_APP_API_URL=http://$ip:5005\" > frontend/.env.local
            docker-compose down -v || true
            docker-compose build --no-cache
            docker-compose up -d
            "


      - name: Initialize DB schema
        run: |
               ip=$(terraform -chdir=budget-infra output -raw public_ip)
                    
               ENDPOINT=$(terraform -chdir=budget-infra output -raw rds_endpoint)
               HOST=$(echo "$ENDPOINT" | cut -d':' -f1 | tr -d '\r\n')

               ssh -i ~/.ssh/myPrivateKey ubuntu@$ip "sudo apt update && sudo apt install -y postgresql-client" 
               ssh -i ~/.ssh/myPrivateKey ubuntu@$ip "
               echo "$HOST" >  "/home/ubuntu/test.txt"
               PGPASSWORD='${{ secrets.DB_PASSWORD }}' psql -h "$HOST" -p 5432 -U postgres -f /home/ubuntu/Budget_Manager_Reloaded/backend/budget_2025-05-08.sql
               "
   